app_post/urls.py
from django.urls import path
from . import views

app_name = 'app_post'
urlpatterns = [
    path('', views.home, name='home'),
    path('create/', views.create_post, name='create_post'),
    path('view/<pk>/', views.view_edit_post, name='view_post')
]

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('', include('app_post.urls', namespace='app_post')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'app_post.views.handler404'

app_post/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

class Post(models.Model):
    id = models.CharField(max_length=100, primary_key=True, editable=False, unique=True, default=uuid.uuid4)
    title = models.CharField(max_length=300)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    body = models.TextField()
    image = models.ImageField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-created']
    
    def __str__(self):
        return self.title

app_post/forms.py
from django.forms import ModelForm
from .models import Post
from django import forms

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'image']
        # labels = {
        #     'title': 'Nazwa',
        #     'image': 'Wgraj'
        # }
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Dodaj tytuł...', 'class': 'text-black dark:text-white rounded-lg w-full dark:bg-[#313338]'}),
            'body': forms.Textarea(attrs={'placeholder': 'Dodaj treść...', 'style': 'resize: none;', 'class': 'text-black dark:text-white w-full rounded-lg outline-none border-white dark:bg-[#313338]'}),
            'image': forms.ClearableFileInput(attrs={'class': 'text-black dark:text-white'}),
        }
        
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        
        for field in self.fields:
            self.fields[field].label = ''
            
            
class EditForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body']
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Dodaj tytuł...', 'class': 'text-2xl text-black dark:text-white rounded-lg w-full dark:bg-[#313338]'}),
            'body': forms.Textarea(attrs={'placeholder': 'Dodaj treść...', 'style': 'resize: none;', 'class': 'text-2xl text-black dark:text-white w-full rounded-lg outline-none border-white dark:bg-[#313338]'}),
        }
        
    def __init__(self, *args, **kwargs):
        super(EditForm, self).__init__(*args, **kwargs)
        
        for field in self.fields:
            self.fields[field].label = ''

app_post/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm, EditForm
import requests
from django.contrib.auth.decorators import login_required
from .models import Post


def home(request):
    posts = Post.objects.all()
    response = requests.get('https://randomuser.me/api/?results=35')
    data = response.json()

    people = []
    if 'results' in data:
        for user in data['results']:
            first_name = user['name']['first']
            last_name = user['name']['last']
            username = user['login']['username']
            picture = user['picture']['medium']
            city = user['location']['city']
            
            people.append({
                'first_name': first_name, 
                'last_name': last_name,
                'username': username,
                'picture': picture,
                'city': city
                 })
    else:
        print('Nie udało się pobrać danych użytkowników')

    return render(request, 'home.html', {'people': people, 'posts': posts})


@login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(data=request.POST, files=request.FILES)
        
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('app_post:home')
    else:
        form = PostForm()
    
    return render(request, 'create_post.html', {'form': form})


def view_edit_post(request, pk):
    post = get_object_or_404(Post, id=pk)
    form = EditForm(instance=post)
    
    if request.method == 'POST':
        form = EditForm(data=request.POST, instance=post)
        
        if form.is_valid():
            form.save()
            return redirect('app_post:home')
    
    return render(request, 'view_post.html', {'post': post, 'form': form})


def handler404(request, exception):
    
    return render(request, '404.html', status=404)

templates/base.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
  <html lang="en" x-data="{ darkMode: localStorage.getItem('dark') === 'true', sidebarOpen: true}" x-init="$watch('darkMode', value => localStorage.setItem('dark', value))" :class="{ 'dark': darkMode, 'light': !darkMode }">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="{% static 'instagram.png' %}" type="image/x-icon" />
    <title>Instagram - clone</title>
    <script>
      function isDarkModeEnabled() {
        const darkMode = localStorage.getItem('dark')
        return darkMode === 'true'
      }
      function applyDarkModeClass() {
        if (isDarkModeEnabled()) {
          document.documentElement.classList.add('dark')
        } else {
          document.documentElement.classList.remove('dark')
        }
      }
      applyDarkModeClass()
    </script>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Concert+One&display=swap" rel="stylesheet">
    {% comment %} <script src="https://cdn.tailwindcss.com"></script> {% endcomment %}
    {% comment %} <link rel="stylesheet" href="{% static 'style.css' %}" /> {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/dist/styles.css' %}" />
    <style type="text/tailwindcss">
      [x-cloak] {
        display: none !important;
      }
    </style>
    {% tailwind_css %} 
  </head>
  <body class="cursor-default min-w-[400px] bg-white dark:bg-[#313338] flex flex-col min-h-screen">
    {% include 'includes/header.html' %} 
      {% block content %}
      
      {% endblock %}
    {% include 'includes/footer.html' %}
  </body>
</html>

templates/create_post.html
{% extends 'base.html' %} {% block content %}
  <section class="flex-grow flex flex-col items-center justify-center">
    <form class="flex flex-col items-center justify-center p-10 rounded-lg bg-[whitesmoke] dark:bg-[#2B2D31] [&>*]:mb-4 [&>*]:w-full" method="POST" enctype="multipart/form-data">
      <h1 class="text-2xl text-black dark:text-white uppercase">Dodaj wpis</h1>
      {% csrf_token %} {{ form.as_p }}
      <button class="uppercase border border-yellow-600 rounded-md bg-yellow-300 px-4 py-2" type="submit">wyślij</button>
    </form>
  </section>
{% endblock %}

templates/home.html
{% extends 'base.html' %} {% load static %} {% block content %}
  <section class="grid grid-cols-3 min-h-screen max-w-screen-2xl mx-auto">
    <div class="col-span-full md:col-span-2 order-2" :class="!sidebarOpen ? 'md:!col-span-3' : 'md:!col-span-2'">
      <sidebarbottom class="flex p-6 m-2 bg-[whitesmoke] dark:bg-[#2B2D31] border border-gray-200 dark:border-[#1E1F22] rounded-lg overflow-x-auto space-x-4 flex-grow transition-all duration-300">
        {% for person in people|slice:':30' %}
          <div class="flex flex-col justify-center items-center mr-3">
            <img class="border-2 border-dotted border-[chocolate] p-1 rounded-full w-12 h-12 md:w-16 md:h-16" src="{{ person.picture }}" />
            <p class="w-[70px] md:w-full truncate md:overflow-visible dark:text-white">{{ person.username }}</p>
          </div>
        {% endfor %}
      </sidebarbottom>

      <main class="flex flex-col items-center justify-center p-2">
        {% for post in posts %}
          <div class="flex flex-col w-full bg-[whitesmoke] dark:bg-[#2B2D31] p-3 rounded-md 2xl:w-[95%] transition-all duration-300">
            <article class="flex flex-col items-center bg-white dark:bg-[#313338] rounded-lg px-4 transition-all duration-300">
              <div class="flex justify-between items-center p-3 w-full border-b mb-4">
                <div class="flex items-center rounded-full">
                  <img class="rounded-full w-12 h-12 cursor-pointer" src="{% static 'avatar_default.png' %}" alt="avatar" />

                  <p class="ml-2 text-gray-400">
                    @author
                    <span class="text-black dark:text-white font-bold transition-all duration-300">kr0pa</span>
                  </p>
                </div>

                <img width="36" height="36" src="https://img.icons8.com/fluency/36/more.png" alt="more" />
              </div>

              <figure>
                <a href="{% url 'app_post:view_post' post.id %}"><img class="w-full object-cover" src="{{ post.image.url }}" alt="" /></a>
              </figure>

              <div class="flex justify-between items-center p-3 w-full border-t mt-4"></div>
            </article>
          </div>
        {% endfor %}
      </main>
    </div>

    <sidebarright x-show="sidebarOpen" class="order-1 col-span-full !flex flex-col m-2 p-2 rounded-md md:col-span-1 bg-[whitesmoke] dark:bg-[#2B2D31] md:order-2" :class="!sidebarOpen && '2xl:fixed top-full left-full'" x-cloak x-transition:enter="duration-300 ease-out" x-transition:enter-start="opacity-0 translate-x-96" x-transition:enter-end="opacity-100 translate-x-0" x-transition:leave="duration-300 ease-in" x-transition:leave-start="opacity-100 translate-x-0" x-transition:leave-end="opacity-0 translate-x-96">
      <div class="flex justify-between items-center space-x-2">
        <div class="flex items-center">
          <img class="rounded-full w-14 h-14" src="{% static 'avatar_default.png' %}" alt="avatar" />

          <div class="ml-2">
            <p class="font-bold dark:text-white transition-all duration-300">kr0pa</p>
            <span class="text-sm text-gray-400">Witaj na Instagramie</span>
          </div>
        </div>

        <a class="text-blue-500" href="/">Wyloguj się</a>
      </div>

      <hr class="mt-3" />

      <div class="flex justify-between items-center my-3">
        <p class="text-gray-400">Polecane dla ciebie</p>
        <p class="font-bold dark:text-white transition-all duration-300">Zobacz wszystko</p>
      </div>

      {% for person in people|slice:'30:' %}
        <div class="flex items-center justify-between my-2 mr-2">
          <div class="flex items-center">
            <img class="rounded-full w-11 h-11" src="{{ person.picture }}" alt="avatar" />

            <div class="md:w-[80%] lg:w-full mx-2">
              <p class="font-bold truncate dark:text-white transition-all duration-300">{{ person.username }}</p>
              <span class="text-xs text-gray-400 truncate">{{ person.first_name }} {{ person.last_name }}</span>
            </div>
          </div>

          <a class="block md:hidden lg:block ml-3 content-end text-blue-500 truncate" href="/">Obserwuj</a>
          <img class="hidden md:block lg:hidden cursor-pointer ml-4" width="30" height="30" x-bind:src="darkMode ? 'https://img.icons8.com/ios-filled/50/FFFFFF/add-user-male.png' : 'https://img.icons8.com/ios-filled/50/add-user-male.png'" alt="add-user-male" />
        </div>
      {% endfor %}
    </sidebarright>

    <sidebararrow x-cloak x-on:click="sidebarOpen = !sidebarOpen" class="hidden md:block 2xl:hidden fixed top-[30%] right-[.5%] cursor-pointer animate-pulse">
      <a><img x-show="!sidebarOpen" class="w-8 ml-1.5 rotate-90" src="https://img.icons8.com/papercut/60/expand-arrow.png" alt="expand-arrow" /></a>

      <a><img x-show="sidebarOpen" class="w-8 ml-1.5 -rotate-90" src="https://img.icons8.com/papercut/60/expand-arrow.png" alt="expand-arrow" /></a>
    </sidebararrow>
  </section>
{% endblock %}

templates/includes/footer.html
<footer class="bg-[whitesmoke] dark:bg-[#0F172A] mt-6 p-2">
  <div class="flex justify-center items-center dark:text-white font-bold text-xs sm:text-sm md:text-base">
    <!-- prettier-ignore-start -->
      Created by <a href="https://kr0pa.pl" target="_blank"><p class="text-[royalblue] mx-1 cursor-pointer text-sm sm:text-base md:text-lg">kr0pa</p></a> educational <p class="mx-1 text-sm sm:text-base md:text-lg">Instagram Clone</p>&copy; 2024

  </div>
</footer>

templates/includes/header.html
{% load static %}

<header class="flex justify-between items-center h-14 bg-[whitesmoke] dark:bg-[#0F172A] py-2 px-4 transition-all duration-300">
  <div class="flex w-36 object-cover cursor-pointer">
    <a href="/"><img x-bind:src="darkMode ? '{% static 'instagram_logo1.png' %}' : '{% static 'instagram_logo2.png' %}'" alt="" /></a>
  </div>

  <div class="hidden md:flex justify-between items-center flex-1">
    <div class="flex-grow text-center select-none">
      <input class="w-5/6 flex-grow rounded-full px-5 py-2 outline-none text-center truncate dark:bg-[#313338] dark:text-white transition-all duration-300" type="text" placeholder="Wpisz tekst..." />
    </div>

    <div class="[&>img]:hidden md:[&>img]:block md:flex items-center space-x-4">
      <a href="/"><img width="24" height="24" x-bind:src="darkMode ? 'https://img.icons8.com/material-rounded/24/FFFFFF/home.png' : 'https://img.icons8.com/material-rounded/24/home.png'" alt="home" /></a>

      <img width="24" height="24" x-bind:src="darkMode ? 'https://img.icons8.com/ios-filled/24/FFFFFF/sent.png' : 'https://img.icons8.com/ios-filled/24/sent.png'" alt="sent" />

      <a href="{% url 'app_post:create_post' %}"><img width="24" height="24" x-bind:src="darkMode ? 'https://img.icons8.com/ios-filled/24/FFFFFF/add--v1.png' : 'https://img.icons8.com/ios-filled/24/add--v1.png'" alt="add--v1" /></a>

      <img width="24" height="24" x-bind:src="darkMode ? 'https://img.icons8.com/fluency-systems-regular/24/FFFFFF/user-group-woman-woman.png' : 'https://img.icons8.com/fluency-systems-regular/24/user-group-woman-woman.png'" alt="user-group-woman-woman" />

      <img width="24" height="24" x-bind:src="darkMode ? 'https://img.icons8.com/ios/24/FFFFFF/like--v1.png' : 'https://img.icons8.com/ios/24/like--v1.png'" alt="like--v1" />

      <img x-on:click="darkMode = !darkMode" class="!ml-8 cursor-pointer" width="28" height="28" x-bind:src="darkMode ? 'https://img.icons8.com/ios-filled/50/FFFFFF/moon-symbol.png' : 'https://img.icons8.com/ios/50/sun--v1.png'" alt="dark-mode" />

      <div class="w-12 h-12 rounded-full">
        <img class="rounded-full w-12 h-12" src="{% static 'avatar_default.png' %}" alt="avatar" />
      </div>
    </div>
  </div>

  <div class="block md:hidden">
    <img class="w-6 h-6 select-none cursor-pointer" x-bind:src="darkMode ? 'https://img.icons8.com/small/64/ffffff/menu.png' : 'https://img.icons8.com/small/64/menu.png'" />
  </div>
</header>

templates/view_post.html
{% extends 'base.html' %}
{% block content %}
  <section id="view_post" class="w-full min-h-screen flex flex-col md:flex-row md:justify-between p-4 max-w-screen-xl xl:mx-auto">
    <figure class="w-full h-full border border-black rounded-lg">
      <img class="md:h-[300px] md:w-[300px] object-contain" src="{{ post.image.url }}" alt="" />
    </figure>

    {% if user == post.author %}
      <form method="POST" class="h-[300px] flex-grow">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="w-full uppercase border border-yellow-600 rounded-md bg-yellow-300 px-4 py-2" type="submit">wyślij</button>
      </form>
    {% endif %}
  </section>
{% endblock %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>